name: auto-approver
run-name: CI for approving PRs

on:
  push:
    branches:
      - "renovate/**"
      - "automated-update-charm-libs"

jobs:
  auto-approve:
    name: Auto-approve and merge pull request
    uses: canonical/identity-team/.github/workflows/pr-auto-approval.yaml@f858d2dce01066546803a4279c3525f053ca7d0f # v1.9.2
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
