name: auto-approver
run-name: CI for approving PRs

on:
  push:
    branches:
      - "renovate/**"
      - "automated-update-charm-libs"

jobs:
  auto-approve:
    name: Auto-approve and merge pull request
    uses: canonical/identity-team/.github/workflows/pr-auto-approval.yaml@7ec3565943646a4abe70497e354edac4357349a8 # v1.9.3
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
