name: auto-approver
run-name: CI for approving PRs

on:
  push:
    branches:
      - "renovate/**"
      - "automated-update-charm-libs"

jobs:
  auto-approve:
    name: Auto-approve and merge pull request
    uses: canonical/identity-team/.github/workflows/pr-auto-approval.yaml@7ca109a149fd39d889d1f66f5d2727aafefc6915 # v1.9.1
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
