name: Render Terraform Docs
on:
  workflow_call:

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs and push changes back to PR branch
        uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # v1.4.1
        with:
          config-file: terraform/.terraform-docs.yaml
          working-dir: terraform
          output-file: MODULE_SPECS.md
          output-method: inject
          git-push: "true"
