# Release charm's libraries if they have changed
name: Release Charm Library

on:
  push:
    tags:
      - "v**"

jobs:
  filter:
    name: Check if charm library changes between tags
    runs-on: ubuntu-latest
    outputs:
      run-release: ${{ steps.check.outputs.run_release }}
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          fetch-depth: 0

      - name: Check diff between latest two tags
        id: check
        run: |
          set -e

          TAGS=$(git tag --sort=-creatordate | grep "^v" | head -n 2)
          LATEST_TAG=$(echo "$TAGS" | sed -n 1p)
          PREV_TAG=$(echo "$TAGS" | sed -n 2p)

          echo "Latest tag: $LATEST_TAG"
          echo "Previous tag: $PREV_TAG"

          echo "run_release=false" >> $GITHUB_OUTPUT

          if git diff --name-only "$PREV_TAG" "$LATEST_TAG" | grep -q '^lib/charms/kratos/'; then
            echo "Changes found in charm library"
            echo "run_release=true" >> $GITHUB_OUTPUT
          else
            echo "No changes found in charm library"
          fi

  release-lib:
    name: Release any bumped library
    needs: filter
    if: needs.filter.outputs.run-release == 'true'
    uses: canonical/identity-team/.github/workflows/charm-libs-release.yaml@7ca109a149fd39d889d1f66f5d2727aafefc6915 # v1.9.1
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
