# reusable workflow for checking library versions and opening PRs to bump
name: Update Charm Libraries

on:
  workflow_call:
    inputs:
      charmcraft_channel:
        description: Channel from which to install charmcraft
        default: 'latest/candidate'
        required: false
        type: string
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true
      PAT_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      charmcraft_channel:
        description: Channel from which to install charmcraft
        default: 'latest/candidate'
        required: false
        type: string

jobs:
  update-libs:
    name: Update charm libraries
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0

      - run: sudo snap install charmcraft --channel ${{ inputs.charmcraft_channel }} --classic

      - name: update charm libs
        run: charmcraft fetch-lib
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_CREDENTIALS }}

      - name: Create Pull Request
        id: create-pull-request
        uses: canonical/create-pull-request@main
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          commit-message: Update charm libs
          branch-name: 'automated-update-charm-libs'
          title: (Automated) Update Charm Libs
          body: Update charm libs
          upsert: true
          ignore-no-changes: true
